#!/bin/sh
# Upload with explicit CCSID conversion: UTF-8(1208) -> EBCDIC English(37)
system "CPYFRMSTMF FROMSTMF('/tmp/TDSTRPGLE_v3.rpgle') TOMBR('/QSYS.LIB/GURILIB.LIB/QRPGLESRC.FILE/TDSTRPGLE.MBR') MBROPT(*REPLACE) STMFCCSID(1208) DBFCCSID(37)"
echo "CPYFRMSTMF: $?"
system "ADDLIBLE LIB(GURILIB)"
system "ADDLIBLE LIB(QIWS)"
system "CRTBNDRPG PGM(GURILIB/TDSTRPGLE) SRCFILE(GURILIB/QRPGLESRC) SRCMBR(TDSTRPGLE) OPTION(*EVENTF) DBGVIEW(*ALL)"
echo "COMPILE: $?"
