#!/bin/sh
system "CPYFRMSTMF FROMSTMF('/tmp/TDSTRPGLE_v5.rpgle') TOMBR('/QSYS.LIB/GURILIB.LIB/QRPGLESRC.FILE/TDSTRPGLE.MBR') MBROPT(*REPLACE) STMFCCSID(1208)"
echo "CPYFRMSTMF: $?"
system "ADDLIBLE LIB(GURILIB)"
system "ADDLIBLE LIB(QIWS)"
system "CRTBNDRPG PGM(GURILIB/TDSTRPGLE) SRCFILE(GURILIB/QRPGLESRC) SRCMBR(TDSTRPGLE) OUTPUT(*PRINT)" 2>&1
echo "COMPILE: $?"
