#!/bin/sh
# Get latest CRTBNDRPG spool file errors
system "DSPJOBLOG JOB(*) OUTPUT(*OUTFILE) OUTFILE(QTEMP/JOBLOG)"
db2 "SELECT MSGID, MSGSEV, MSGDTA FROM QTEMP/JOBLOG WHERE MSGSEV >= 20 ORDER BY TIMESTAMP DESC FETCH FIRST 30 ROWS ONLY" 2>&1 | head -60
